# permissions for end users to edit remoteexecnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: remoteexecnodes-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: yt-k8s-operator
    app.kubernetes.io/part-of: yt-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: remoteexecnodes-editor-role
rules:
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remoteexecnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remoteexecnodes/status
  verbs:
  - get
