# yaml-language-server: $schema=https://raw.githubusercontent.com/ytsaurus/ytsaurus-k8s-operator/refs/heads/main/config/crd/schema/cluster.ytsaurus.tech_remoteytsaurus_v1.json

apiVersion: cluster.ytsaurus.tech/v1
kind: RemoteYtsaurus
metadata:
  name: remote-ytsaurus
spec:
  cellTag: 1
  # FIXME: Must be optional.
  cellTagMasterCaches: 1
  # FIXME Lookup master endpoints via service.
  hostAddresses:
    - ms-0.masters.ytsaurus.svc
