# yaml-language-server: $schema=https://raw.githubusercontent.com/ytsaurus/ytsaurus-k8s-operator/refs/heads/main/config/crd/schema/cluster.ytsaurus.tech_spyt_v1.json

apiVersion: cluster.ytsaurus.tech/v1
kind: Spyt
metadata:
  labels:
    app.kubernetes.io/name: spyt
    app.kubernetes.io/instance: spyt-sample
    app.kubernetes.io/part-of: ytsaurus-k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ytsaurus-k8s-operator
  name: myspyt
spec:
  ytsaurus:
    name: minisaurus
  image: ghcr.io/ytsaurus/spyt:2.8.2
  sparkDistribOffline: true
  sparkVersions:
    - "3.2.2"
    - "3.5.7"
