# yaml-language-server: $schema=https://raw.githubusercontent.com/ytsaurus/ytsaurus-k8s-operator/refs/heads/main/config/crd/schema/cluster.ytsaurus.tech_chyt_v1.json

apiVersion: cluster.ytsaurus.tech/v1
kind: Chyt
metadata:
  name: mychyt
spec:
  ytsaurus:
    name:
      minisaurus
  image: ghcr.io/ytsaurus/chyt:2.14.0-relwithdebinfo
  makeDefault: true
  createPublicClique: true
