name: Build and test

on:
  push:
    branches:
      - main

jobs:
# Temporary remove tests from run to configure ghcr upload
#  check-unit:
#    name: Run unit tests
#    uses: ./.github/workflows/subflow_run_unit_tests.yaml
#
#  check-e2e:
#    name: Run e2e tests
#    needs:
#      - check-unit
#    uses: ./.github/workflows/subflow_run_e2e_tests.yaml
#
#  check-compat:
#    name: Run compat tests
#    needs:
#      - check-e2e
#    uses: ./.github/workflows/subflow_run_compat_tests.yaml

  release-nightly:
    name: Release nightly image
    needs:
      - check-compat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker Hub login
        run: |
          echo '${{ secrets.DOCKER_HUB_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_HUB_LOGIN}} --password-stdin

      # Uses the `docker/login-action` action to log in to the Container registry
      # using the account and password that will publish the packages.
      # Once published, the packages are scoped to the account defined here.
      - name: Guthub Packages Login
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make release RELEASE_VERSION=0.0.$(git rev-list --count HEAD)-dev-${GITHUB_SHA} OPERATOR_IMAGE=ytsaurus/k8s-operator-nightly OPERATOR_CHART=ytop-chart-nightly

  send-notifications:
    name: Send notifications
    needs:
      - release-nightly
    runs-on: trampoline
    if: ${{ failure() }}
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            Workflow *${{github.workflow}}* failed: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}.
            Commit: ${{github.event.head_commit.sha}}
            Message:
            ```
            ${{github.event.head_commit.message}}
            ```
